create table comment (id bigint not null auto_increment, text varchar(255), user_id bigint, primary key (id));
create table date_trip (id bigint not null auto_increment, trip date, maintenance_id bigint, primary key (id));
create table fn (id bigint not null auto_increment, days date, format varchar(255), primary key (id));
create table lk (id bigint not null auto_increment, code_administrator integer not null, contact varchar(255), factory_number varchar(255), pass varchar(255), primary key (id));
create table maintenance (id bigint not null auto_increment, limitation date, name varchar(255), product_id bigint, primary key (id));
create table ofd (id bigint not null auto_increment, contact varchar(255), days date, pass varchar(255), product_id bigint, primary key (id));
create table operator (id bigint not null auto_increment, name varchar(255), primary key (id));
create table organization (id bigint not null auto_increment, name varchar(255), primary key (id));
create table product (id bigint not null auto_increment, address varchar(255), name varchar(255), number integer not null, fn_id bigint, lk_id bigint, ofd_id bigint, operator_id bigint, user_id bigint, primary key (id));
create table request (id bigint not null auto_increment, date_of_created datetime(6), date_of_end datetime(6), client_id bigint, product_id bigint, primary key (id));
create table requisite (id bigint not null auto_increment, inn integer not null, kpp integer not null, ogrn integer not null, organization_id bigint, primary key (id));
create table tariff (id bigint not null auto_increment, limitation date, name varchar(255), primary key (id));
create table topic (id bigint not null auto_increment, request_id bigint, primary key (id));
create table user (id bigint not null auto_increment, active bit not null, email varchar(255), last_name varchar(255), name varchar(255), password varchar(255), patronymic varchar(255), phone_number varchar(255), status varchar(255), requisite_id bigint, primary key (id));
create table user_role (user_id bigint not null, roles varchar(255));
alter table comment add constraint FK8kcum44fvpupyw6f5baccx25c foreign key (user_id) references user (id);
alter table date_trip add constraint FK7a8sp8ushqxxurc7v5c7k87ry foreign key (maintenance_id) references maintenance (id);
alter table maintenance add constraint FK23v17poto7hxopwwo0uwiigo6 foreign key (product_id) references product (id);
alter table ofd add constraint FKfgy7p5rffoiva5awr307ft06g foreign key (product_id) references product (id);
alter table product add constraint FKplkaxgyevvjrfwr2hjn0g247h foreign key (fn_id) references fn (id);
alter table product add constraint FKs2nyiweev1txcvh12tbo9218y foreign key (lk_id) references lk (id);
alter table product add constraint FKsxebnj67msed3buksd8t2ykqn foreign key (ofd_id) references ofd (id);
alter table product add constraint FKkj7qye7p1d0uar334u6oawmo2 foreign key (operator_id) references operator (id);
alter table product add constraint FK979liw4xk18ncpl87u4tygx2u foreign key (user_id) references user (id);
alter table request add constraint FKex2mlbjmdxtuwbu7tacnehsq0 foreign key (client_id) references user (id);
alter table request add constraint FKbywsb4tohr9bviei9hqvp7r4i foreign key (product_id) references product (id);
alter table requisite add constraint FKr2n1dx4o6cydn31exu84v0btd foreign key (organization_id) references organization (id);
alter table topic add constraint FK3ttv8rmj9cue1843c6ue5bca7 foreign key (request_id) references request (id);
alter table user add constraint FKc4934fi2itfot260tkllrs6q6 foreign key (requisite_id) references requisite (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);

